Feature/hrs 11
bcastillo-2022474/hotel-reservation-system-backend pull request #7
Opened 2024-04-24 03:52 UTC by darriola2021670

Hice modelo, controller y routes de booking y arregle unos errores mios

2024-04-24 21:36 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +    bookingModel.find(query).desde(Number(desde)).limit(Number(limit)),
2 Cosas, el metodod `desde` no existe, ademas de eso, estas trabajando con Spanglish, ese necesario que trabajes en ingles TODO, tanto los query params como los nombres de las variables. el codigo corregido deberia quedar algo asi:

```javascript
bookingModel.find(query).skip(page * limit).limit(limit)
```

2024-04-24 21:36 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +      msg: "Reserva no encontrada",
Mensajes deberian estar en ingles. en el front nosotros manejaremos las excepciones y la UI en español.

2024-04-24 21:39 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +      msg: "Reserva no encontrada",
Porfavor trabajar en ingles

2024-04-24 21:39 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +    msg: "Reserva actualizada exitosamente",
Porfavor trabajar en ingles

2024-04-24 21:39 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +      msg: "Reserva no encontrada",
Porfavor trabajar en ingles

2024-04-24 21:40 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +    msg: "Reserva eliminada exitosamente",
Porfavor trabajar en ingles

2024-04-24 21:43 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +};
Aqui hace falta muchas mas validaciones. necesitamos vincular el Booking con el usuario que lo hizo, y con el hotel. toda esa data no la estas pasando esto deberia tirar error, segun validaciones de DB.
![imagen](https://github.com/kinal-team-1/hotel-reservation-system-backend/assets/98283465/e6ec2557-f397-4caa-9f50-202cde650063)

Como puedes ver en la imagen el unico campo que puede ser null (osea que no es requerido) es el `updated_at` por lo que deberias de pasarle toda la data al booking post

2024-04-24 21:45 UTC, bcastillo-2022474 commented on src/model/booking.model.js
> +export default bookingModel;
Aqui faltan muchos campos. ver el modelo, y los datos compartidos en la [documentacion del proyecto](https://github.com/bcastillo-2022474/docs-proyecto-grupal/blob/master/entidad_relacion.md)

2024-04-24 21:46 UTC, bcastillo-2022474 commented on src/routes/booking.routes.js
> +);
Excelente manejo de validaciones y middlewares

2024-04-24 21:50 UTC, bcastillo-2022474 commented on src/routes/booking.routes.js
> +);
muy bien, pero, deberias validar los demas campos que hacen falta en tu modelo. ademas, los campos deben ser opcionales en el caso de put. puedes usar este ejemplo:

```javascript
router.put(
  "/:id",
  [
    validateJwt,
    isAdminLogged, // este middleware en tu caso no es necesario
    param("id").isMongoId(),
    body("name", "La actualizacion de nombre del hotel no puede estar vacia")
      .optional()
      .isLength({ min: 4 }),
    body(
      "country",
      "Al actualizar el pais el espacio no tiene que dejar el espacio vacio",
    )
      .optional()
      .isLength({ min: 3 }),
    body("address", "La direccion puede ser mas especifica")
      .optional()
      .isLength({ min: 10 }),
    body(
      "description",
      "La direccion se necesita que ser mas accesible in entendible para los clientes",
    )
      .optional()
      .isLength({ min: 30 }),
    validateRequestParams,
  ],
  putHotel,
);
```

Puedes tambien tomar de referencia el CRUD de hoteles y sus rutas

2024-04-24 21:53 UTC, bcastillo-2022474 commented on src/routes/booking.routes.js
> +);
las validaciones no son suficientes. no solo necesito validar que no esten vacios los campos, pero deberias tambien validar que sean fechas validas, tambien cabe aclarar que `tp_status` no es un campo que nos envie el usuario. mas bien es un campo que nosotros seteamos a la hora de crear, editar y eliminar una entidad. Este param tp_status NO deberia ser pasado por el usuario. este param deberia ser `ACTIVE` por defecto y a la hora de eliminar una entidad deberias simplemente cambiar `tp_status` a `INACTIVE`.

2024-04-24 21:54 UTC, bcastillo-2022474 commented on src/routes/booking.routes.js
> +);
Ademas recuerda trabajar con español

2024-04-24 22:02 UTC, bcastillo-2022474 requested changes
Necesito que arregles el modelo, las validaciones, el spanglish, y que no se pueda recibir el tp_status, ese no deberia ser posible cambiarlo desde la request. solo nosotros podemos cambiar esa propiedad dentro de los controladores. Tomar de referencia el CRUD de hoteles, auth y usuarios

2024-04-24 22:02 UTC, bcastillo-2022474 commented on src/routes/booking.routes.js
> +    param("id", "No es un id válido").isMongoId(),
Esta bien, pero de nuevo, trabaja con Ingles

2024-04-24 22:02 UTC, bcastillo-2022474 commented on src/routes/booking.routes.js
> +);
Por cierto, `tp_status` NO deberia ser pasado por el usuario!

2024-04-24 22:02 UTC, bcastillo-2022474 commented on src/routes/booking.routes.js
> +);
Pero hace falta trabajar con ingles, y porfavor usar `page` en vez de `desde` y cambiar implementacion para que use `skip(page * limit)...`

2024-04-24 22:02 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +};
tp_status no deberia ser pasado por el usuario. a la hora de creacion se deberia poner "ACTIVE" por defecto. tomar de referencia hoteles o usuarios CRUD

2024-04-24 22:02 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +  });
de nuevo. tp_status no deberia ser modificado por el que hace la request. no deberias validar si viene o no ese campo ni tampoco usarlo para cambiar una entidad.

2024-04-25 04:10 UTC, darriola2021670 commented
Arregle lo que me pediste los errores, cosas que me faltaban y los cambios de español a ingles

2024-04-26 03:06 UTC, bcastillo-2022474 commented on src/model/booking.model.js
> +  },
`tp_status` deberia tener por defecto `"ACTIVE"`
```suggestion
  tp_status: {
    type: String,
    required: [true, "El estado del hotel es requerido"],
    enum: ["ACTIVE", "INACTIVE"],
    default: "ACTIVE"
  },
```

2024-04-26 03:26 UTC, bcastillo-2022474 commented on src/routes/booking.routes.js
> +);
esto esta mal implemetado, primero, optional deberia ser el primer metodo, segundo, de ser definido, tienes que validar que sea una fecha valida por ejemplo.
```suggestion
router.put(
  "/:id",
  [
    validateJwt,
    param("id").isMongoId(),
    body("date_start", "If defined, start date must be defined as YYYY-MM-DD").optional().custom((date) => {
      if (!date typeof string) throw new Error("Date must be a string");
      if (date.split("-").length === 3) throw new Error("Date not valid");
      const [year, month, day] = date.split("-");
      const isValidDate = Date,validate(year, month, day)
      
      if (!isValidDate) throw new Error("Date not valid");
    })
    // ... demas validaciones
    body("tp_status").isEmpty().withMessage("tp_status is not allowed"), // Validar que tp_status no sea proporcionado por el usuario
    validateRequestParams,
  ],
  putBooking,
);
```

ese es solo un ejemplo de como hacerlo, tambien te podrias apoyar con otros metodos ya definidos, lo que quiero es que dejes de solo validar `notEmpty`. puedes guiarte de la [documentacion](https://express-validator.github.io/docs/guides/validation-chain) y tambien te pudes guiar de este proyecto, y [este](https://github.com/bcastillo-2022474/gestion-ventas/blob/master/src/category/category.routes.js) ejemplo en particular y [este](https://github.com/bcastillo-2022474/gestion-ventas/blob/master/src/products/product.routes.js), tambien echale un ojo a [este](https://github.com/bcastillo-2022474/gestion-ventas/blob/master/src/user/user.routes.js), lo que si me esta gustando bastante es el metodo de `withMessage(message)`, sigue utilizando ese metodo para definir los mensajes de nuestros middlewares. tambien te recomiendo que mires en la [doc oficial](https://express-validator.github.io/docs/api/validation-chain/#built-in-validators) en donde estan todos los metodos que podes usar, y toma en cuenta que el orden en el que llamas a los validadores importa, [leer esto](https://express-validator.github.io/docs/guides/validation-chain#chaining-order), es super important

2024-04-26 03:28 UTC, bcastillo-2022474 commented on src/routes/booking.routes.js
> +);
esto esta muy bien, peeeeeeeeeeeero, el `room` y `user` NO deben ser opcionales, estos DEBEN SER REQUERIDOS, lo mismo en el modelo, estos campos deben ser requeridos, todos los campos menos `updatedAt` son requeridos si no estoy mal.

2024-04-26 03:29 UTC, bcastillo-2022474 commented on src/routes/booking.routes.js
> +);
MUY BIEN, el orden aqui si que esta bien, podrias validar que los numeros sean enteros y no decimales, pero ya como lo tenes esta bien

2024-04-26 03:30 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +  }
mmmm, esta validacion esta mal, pues, room_id y user_id van a ser MongoIds y los mongos IDs son alfanumericos, ademas este tipo de validaciones iria en un custom middleware no dentro del controlador.

2024-04-26 03:34 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +};
muy bien, pero recuerda que `limit` y `page` al ser query params, si no estoy mal, son strings siempre, entonces, hay que convertirlos a numeros.
```suggestion
  const { limit, page } = req.query;
  const query = { tp_status: "ACTIVE" };

  const [total, bookings] = await Promise.all([
    bookingModel.countDocuments(query),
    bookingModel.find(query).skip(Number(page) * Number(limit)).limit(Number(limit))
  ]);

  res.status(200).json({
    total,
    bookings,
  });
};
```

de cualquier forma, muy bien los cambios, y de ser cierto lo que te digo, deberias validar que los query params, sean strings que se puedan convertir a numeros enteros validos, no solo si son numeros, pues seguramente fallara ese middleware

2024-04-26 03:35 UTC, bcastillo-2022474 requested changes
Vas muy bien, pero necesito que implementes los cambios que te di. esto es la base de los demas proyectos que estaremos desarrollando, entonces es necesario que hagas bien este PR para que asi en las siguientes tasks, sepas como hacer todo correctamente

2024-04-26 06:54 UTC, darriola2021670 commented
Hice los cambios de controller y routes de booking y un pequeño arreglo en el model

2024-04-26 16:36 UTC, bcastillo-2022474 commented on src/model/booking.model.js
> +  },
A esto me refiero con definir por defecto "ACTIVE", ahora cada que crees un `Booking` y de no definirle el tp_status, tomara este valor.

2024-04-26 16:42 UTC, bcastillo-2022474 commented on src/routes/booking.routes.js
> +    }),
Esto esta maaaaaaaaaal, todavia te dije que te guiaras de la docuemntacion, o que si quiera le preguntaras a GPT, yo hice una parte de esa validacion mal aproposito para que lo arreglaras. necesito que, ya sea que implementes de buena manera una validacion de las que ya trae express-validator, para validar que la fecha esta bien o que, en su defecto, hagas una custom validation, pero necesito que este bien, que valides que funcione, que la feccha agarre,, lo ideal seria que todos tus enpoints los estes probando, que levantes la api y probes si funciona o no tus endpoints, que pasa si lo pones en otros formatos la fecha, que pasa si le pasas un numero, un booleano, que pasa si le pasas MM-DD-YYYY en vez de YYYY-MM-DD, que pasa si le pasas YY-MM-DD, todo eso necesito que lo probes, y que verifiques que el endpoint da error cuando deba dar error y que funcione cuando deba funcionar, ya te deje varios links con informacion al respecto y ejemplos, necesito que te impliques.

2024-04-26 16:46 UTC, bcastillo-2022474 commented on src/routes/booking.routes.js
> +);
Esta bien, pero, toma en cuenta como funcina el endpoint `isISO8601` que es lo que hace, como es que esperas las fechas y que es lo que va pasar. lo que quiero es que me dez una interfaz estable en como comunicarme tanto ne el post como en el put, ambos deben funcionar casi casi igual, reciben los mismos campos, lo unico que en put todos son opcionales y hay algunos campos que no los tomamos en cuenta por simplicidad, pero, vamos, que es lo mismo, necesito que arregles esto del middleware de las fechas. hasta que no vea yo que sea consistente, no te pasare la PR.

2024-04-26 16:48 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +  });
Esto de setear el tp_status es innecesario pues a nivel de base de datos (me refiero al modelo), pusiste que por defecto, de no ser definido, `tp_status` iba a ser "ACTIVE".

2024-04-26 16:52 UTC, bcastillo-2022474 requested changes
Ya arreglaste casi todo. pero necesito que te impliques con los middlewares de las fechas, necesito que valides bien que viene en un formato en especifico, ya sea YYYY-MM-DD, o DD-MM-YYYY, o que venga en formato ISO, o como querras, pero que tanto en el POST como en el PUT usen el mismo formato consistentemente, y que este bien testeado. proba esos 2 endpoints en POSTMAN/Thunder porfa, y cuando ambos esten bien validados me haces la PR.

2024-04-28 00:54 UTC, darriola2021670 commented
se hicieron cambios que me pediste

2024-04-28 02:12 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +  const tp_status = "ACTIVE";
esta variable si no la vas a usar, debes eliminarla. lo voy a arreglar yo, pero necesito lo tengas en cuenta

2024-04-28 02:53 UTC, bcastillo-2022474 commented on src/controller/booking.controller.js
> +  });
en el modelo esta esperando que le devuelvas `user` y `room` en vez de `user_id` y `room_id`, eso me dice que no probaste los endpoints. necesito que revises mucho mas a fondo tus tareas, me consume demasiado tiempo, revisar cada endpoint.
```suggestion
  const booking = new bookingModel({
    date_start,
    date_end,
    room: room_id,
    user: user_id,
  });
```

2024-04-28 02:54 UTC, bcastillo-2022474 approved these changes
Esta bien, hay algunos cosas que no estan bien, por ejemplo, las validaciones en el modelo las dejaste en español, los endpoints no los probaste. pero, dentro de todo, seinto que ya aprendiste como deben ser las demas tareas.

2024-04-28 05:47 UTC, merged